/* tslint:disable */
/* eslint-disable */
/**
 * SoWeCanJustBeFriends
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FlankUser
 */
export interface FlankUser {
    /**
     * 
     * @type {string}
     * @memberof FlankUser
     */
    id?: any | null;
    /**
     * 
     * @type {string}
     * @memberof FlankUser
     */
    userName?: any | null;
    /**
     * 
     * @type {string}
     * @memberof FlankUser
     */
    normalizedUserName?: any | null;
    /**
     * 
     * @type {string}
     * @memberof FlankUser
     */
    email?: any | null;
    /**
     * 
     * @type {string}
     * @memberof FlankUser
     */
    normalizedEmail?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof FlankUser
     */
    emailConfirmed?: any;
    /**
     * 
     * @type {string}
     * @memberof FlankUser
     */
    passwordHash?: any | null;
    /**
     * 
     * @type {string}
     * @memberof FlankUser
     */
    securityStamp?: any | null;
    /**
     * 
     * @type {string}
     * @memberof FlankUser
     */
    concurrencyStamp?: any | null;
    /**
     * 
     * @type {string}
     * @memberof FlankUser
     */
    phoneNumber?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof FlankUser
     */
    phoneNumberConfirmed?: any;
    /**
     * 
     * @type {boolean}
     * @memberof FlankUser
     */
    twoFactorEnabled?: any;
    /**
     * 
     * @type {Date}
     * @memberof FlankUser
     */
    lockoutEnd?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof FlankUser
     */
    lockoutEnabled?: any;
    /**
     * 
     * @type {number}
     * @memberof FlankUser
     */
    accessFailedCount?: any;
    /**
     * 
     * @type {string}
     * @memberof FlankUser
     */
    nickname?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof FlankUser
     */
    active: any;
    /**
     * 
     * @type {Array&lt;Loan&gt;}
     * @memberof FlankUser
     */
    loansBorrower?: any | null;
    /**
     * 
     * @type {Array&lt;Loan&gt;}
     * @memberof FlankUser
     */
    loansLender?: any | null;
    /**
     * 
     * @type {Array&lt;Ledger&gt;}
     * @memberof FlankUser
     */
    ledgerEntries?: any | null;
}
