/* tslint:disable */
/* eslint-disable */
/**
 * SoWeCanJustBeFriends
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LedgerInfoModel
 */
export interface LedgerInfoModel {
    /**
     * 
     * @type {string}
     * @memberof LedgerInfoModel
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof LedgerInfoModel
     */
    loanId?: any;
    /**
     * 
     * @type {string}
     * @memberof LedgerInfoModel
     */
    agentId?: any | null;
    /**
     * 
     * @type {Date}
     * @memberof LedgerInfoModel
     */
    timestamp?: any;
    /**
     * 
     * @type {number}
     * @memberof LedgerInfoModel
     */
    totalAmount?: any | null;
    /**
     * 
     * @type {number}
     * @memberof LedgerInfoModel
     */
    paidAmount?: any | null;
    /**
     * 
     * @type {number}
     * @memberof LedgerInfoModel
     */
    weight?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof LedgerInfoModel
     */
    seen?: any;
    /**
     * 
     * @type {boolean}
     * @memberof LedgerInfoModel
     */
    accepted?: any | null;
}
