/* tslint:disable */
/* eslint-disable */
/**
 * SoWeCanJustBeFriends
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LedgerCreateModel
 */
export interface LedgerCreateModel {
    /**
     * 
     * @type {string}
     * @memberof LedgerCreateModel
     */
    loanId: any;
    /**
     * 
     * @type {number}
     * @memberof LedgerCreateModel
     */
    totalAmount?: any | null;
    /**
     * 
     * @type {number}
     * @memberof LedgerCreateModel
     */
    paidAmount?: any | null;
    /**
     * 
     * @type {number}
     * @memberof LedgerCreateModel
     */
    weight?: any | null;
}
