/* tslint:disable */
/* eslint-disable */
/**
 * SoWeCanJustBeFriends
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Ledger
 */
export interface Ledger {
    /**
     * 
     * @type {string}
     * @memberof Ledger
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Ledger
     */
    loanId: any;
    /**
     * 
     * @type {string}
     * @memberof Ledger
     */
    agentId: any;
    /**
     * 
     * @type {Date}
     * @memberof Ledger
     */
    timestamp: any;
    /**
     * 
     * @type {number}
     * @memberof Ledger
     */
    totalAmount?: any | null;
    /**
     * 
     * @type {number}
     * @memberof Ledger
     */
    paidAmount?: any | null;
    /**
     * 
     * @type {number}
     * @memberof Ledger
     */
    weight?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof Ledger
     */
    seen: any;
    /**
     * 
     * @type {boolean}
     * @memberof Ledger
     */
    accepted?: any | null;
    /**
     * 
     * @type {Loan}
     * @memberof Ledger
     */
    loan?: any;
    /**
     * 
     * @type {FlankUser}
     * @memberof Ledger
     */
    agent?: any;
}
