/* tslint:disable */
/* eslint-disable */
/**
 * SoWeCanJustBeFriends
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LoanCreateModel
 */
export interface LoanCreateModel {
    /**
     * 
     * @type {string}
     * @memberof LoanCreateModel
     */
    lenderEmail: any;
    /**
     * 
     * @type {number}
     * @memberof LoanCreateModel
     */
    totalAmount: any;
    /**
     * 
     * @type {number}
     * @memberof LoanCreateModel
     */
    weight: any;
}
