/* tslint:disable */
/* eslint-disable */
/**
 * SoWeCanJustBeFriends
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Loan
 */
export interface Loan {
    /**
     * 
     * @type {string}
     * @memberof Loan
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Loan
     */
    lenderId: any;
    /**
     * 
     * @type {string}
     * @memberof Loan
     */
    borrowerId: any;
    /**
     * 
     * @type {string}
     * @memberof Loan
     */
    startDate: any;
    /**
     * 
     * @type {FlankUser}
     * @memberof Loan
     */
    borrower?: any;
    /**
     * 
     * @type {FlankUser}
     * @memberof Loan
     */
    lender?: any;
    /**
     * 
     * @type {Array&lt;Ledger&gt;}
     * @memberof Loan
     */
    ledgerEntries?: any | null;
}
