/* tslint:disable */
/* eslint-disable */
/**
 * SoWeCanJustBeFriends
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface LoanInfoModel
 */
export interface LoanInfoModel {
    /**
     * 
     * @type {string}
     * @memberof LoanInfoModel
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof LoanInfoModel
     */
    lenderId?: any;
    /**
     * 
     * @type {string}
     * @memberof LoanInfoModel
     */
    borrowerId?: any;
    /**
     * 
     * @type {number}
     * @memberof LoanInfoModel
     */
    totalAmount?: any;
    /**
     * 
     * @type {number}
     * @memberof LoanInfoModel
     */
    paidAmount?: any;
    /**
     * 
     * @type {number}
     * @memberof LoanInfoModel
     */
    weight?: any;
    /**
     * 
     * @type {Date}
     * @memberof LoanInfoModel
     */
    startDate?: any;
}
