/* tslint:disable */
/* eslint-disable */
/**
 * SoWeCanJustBeFriends
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface LoginInfoModel
 */
export interface LoginInfoModel {
  /**
   *
   * @type {string}
   * @memberof LoginInfoModel
   */
  id?: any
  /**
   *
   * @type {string}
   * @memberof LoginInfoModel
   */
  email?: any | null
  /**
   *
   * @type {string}
   * @memberof LoginInfoModel
   */
  fullName?: any | null
  /**
   *
   * @type {string}
   * @memberof LoginInfoModel
   */
  userName?: any | null
  /**
   *
   * @type {string}
   * @memberof LoginInfoModel
   */
  phone?: any | null
  /**
   *
   * @type {string}
   * @memberof LoginInfoModel
   */
  avatar?: any | null
  /**
   *
   * @type {string}
   * @memberof LoginInfoModel
   */
  token?: any | null
  /**
   *
   * @type {Date}
   * @memberof LoginInfoModel
   */
  expiration?: any
}
