/* tslint:disable */
/* eslint-disable */
/**
 * SoWeCanJustBeFriends
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserCreateModel
 */
export interface UserCreateModel {
    /**
     * 
     * @type {string}
     * @memberof UserCreateModel
     */
    email: any;
    /**
     * 
     * @type {string}
     * @memberof UserCreateModel
     */
    password: any;
    /**
     * 
     * @type {string}
     * @memberof UserCreateModel
     */
    fullName?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UserCreateModel
     */
    userName?: any | null;
    /**
     * 
     * @type {string}
     * @memberof UserCreateModel
     */
    phone?: any | null;
}
